version: "3.9"
services:
  # lavalink:
  #   container_name: lavalink
  #   build:
  #     dockerfile: docker/lavalink.dockerfile
  #     context: .
  #   restart: unless-stopped
  rpmtw_discord_bot:
    container_name: rpmtw_discord_bot
    build:
      dockerfile: docker/deploy.dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
    # depends_on:
    #   lavalink:
    #     condition: service_started
