version: "3.9"
services:
  lavalink:
    build:
      dockerfile: docker/lavalink.dockerfile
      context: .
    ports:
      - 2333:2333
    container_name: lavalink
  rpmtw_discord_bot:
    build:
      dockerfile: docker/deploy.dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/data
    container_name: rpmtw-discord-bot
    depends_on:
      - lavalink
    links:
      - lavalink
