name: rpmtw_discord_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-134.1.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  dotenv: ^3.0.0
  nyxx: ^3.2.3
