name: rpmtw_discord_bot
description: RPMTW Discord Server Bot
version: 1.0.0
homepage: https://www.rpmtw.com

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dotenv: ^3.0.0
  hive: ^2.1.0
  nyxx: ^3.4.0
  nyxx_commander: ^3.0.0
  nyxx_extensions: ^3.0.0
  nyxx_interactions: ^4.1.0
  nyxx_lavalink: ^3.0.1
  nyxx_pagination: ^2.2.0
  path: ^1.8.1
  rpmtw_api_client: ^1.0.7+3
  html: ^0.15.0
  http: ^0.13.4
  instant: ^0.4.1
  intl: ^0.17.0
  rpmtw_dart_common_library: ^0.0.3

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  lints: ^1.0.0