name: rpmtw_discord_bot
description: RPMTW Discord Server Bot
version: 1.0.0
homepage: https://www.rpmtw.com

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  hive: ^2.1.0
  nyxx: ^4.0.0
  nyxx_interactions: ^4.3.1
  nyxx_lavalink: ^3.1.0
  nyxx_pagination: ^2.3.0
  path: ^1.8.1
  rpmtw_api_client: ^1.0.9+3
  html: ^0.15.0
  http: ^0.13.4
  instant: ^0.4.1
  intl: ^0.17.0
  rpmtw_dart_common_library: ^0.0.4

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  lints: ^2.0.0
