name: rpmtw_discord_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  dotenv: ^3.0.0
  nyxx: ^3.2.7
  nyxx_commander: ^3.0.0
  nyxx_extensions: ^3.0.0
  nyxx_interactions: ^3.3.0
  nyxx_lavalink: ^3.0.0
  nyxx_pagination: ^2.1.0
  path: ^1.8.1
  rpmtw_api_client: ^1.0.7+3
