name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and setup on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPMTW_SERVER_SSH_HOST }}
          username: ${{ secrets.RPMTW_SERVER_SSH_USERNAME }}
          password: ${{ secrets.RPMTW_SERVER_SSH_PASSPHRASE }}
          key: ${{ secrets.RPMTW_SERVER_SSH_KEY }}
          script: |
            cd ./RPMTW-Discord-Bot
            git pull
            docker-compose pull
            docker-compose down
            docker-compose build
            docker-compose up -d