name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and setup on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPMTW_SERVER_SSH_HOST }}
          username: ${{ secrets.RPMTW_SERVER_SSH_USERNAME }}
          key: ${{ secrets.RPMTW_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.RPMTW_SERVER_SSH_PASSPHRASE }}
          script: |
            cd ./RPMTW-Discord-Bot
            sudo git pull
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d
      - name: Dart Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-warnings: false
          annotate: true
          annotate-only: false
